# Generated by Django 5.0.1 on 2025-12-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('start_date', models.CharField(help_text='e.g., November 2025', max_length=50)),
                ('end_date', models.CharField(blank=True, help_text='e.g., Present or December 2025', max_length=50, null=True)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order for display (higher number appears first)')),
            ],
            options={
                'ordering': ['-order', '-start_date'],
            },
        ),
    ]
